# Generated by Django 5.2 on 2025-06-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_is_active_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='daily_calorie_goal',
            field=models.IntegerField(default=2000),
        ),
    ]
